input {
  beats {
    port => 5044
  }
}

filter {
  if [fields][service] {
    mutate {
      add_field => { "[@metadata][target_index]" => "finova-%{[fields][service]}-%{+YYYY.MM.dd}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "finova-logs-%{+YYYY.MM.dd}" }
    }
  }

  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} +%{LOGLEVEL:log_level} +%{NUMBER:pid} --- \[%{DATA:thread}\] %{DATA:logger} +: %{GREEDYDATA:log_message}" }
    overwrite => ["message"]
    tag_on_failure => ["_grokparsefailure_spring"]
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
    remove_field => ["timestamp"]
  }

  if [log_level] == "ERROR" {
    mutate { add_tag => ["error"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  if "error" in [tags] {
    stdout {
      codec => rubydebug
    }
  }
}
