spring.cloud.vault.uri=${VAULT_URI:https://vault.finovabank.com:8200}
spring.cloud.vault.authentication=KUBERNETES
spring.cloud.vault.kubernetes.role=finovabank-app
spring.cloud.vault.kubernetes.service-account-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
spring.cloud.vault.generic.backend=secret
spring.cloud.vault.generic.default-context=finova
spring.cloud.vault.ssl.trust-store=classpath:vault-truststore.jks
spring.cloud.vault.ssl.trust-store-password=${VAULT_TRUSTSTORE_PASSWORD}
spring.cloud.vault.fail-fast=true
