vault:
  uri: ${VAULT_URI:https://vault.finovabank.com:8200}
  authentication: KUBERNETES
  kubernetes:
    role: finovabank-app
  secrets:
    db-username: ${VAULT_SECRET_DB_USERNAME}
    db-password: ${VAULT_SECRET_DB_PASSWORD}
    mongo-username: ${VAULT_SECRET_MONGO_USERNAME}
    mongo-password: ${VAULT_SECRET_MONGO_PASSWORD}
